### ISSUE TITLE
краш

### ISSUE THREAD

**Issue by MrDoni98** [Tarik02/PocketMine#1]
В консоли:
[Server thread/WARNING]: RuntimeException: "mysqli::mysqli(): (HY000/2002): ▒▒▒▒▒▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒, ▒.▒. ▒▒▒▒▒" (E_WARNING) in "/love.phar/src/Tarik02/Love/provider/MySQLDataProvider" at line 24
В краш файле:
Error: Call to a member function close() on null
File: /love.phar/src/Tarik02/Love/Love
Line: 431
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Love v1.0.0

Code:
[422] 		};
[423] 		if (!$this->provider)
[424] 			$this->provider = new DummyDataProvider($this);
[425] 
[426] 		$this->getServer()->getPluginManager()->registerEvents($this,$this);
[427] 	}
[428] 	public function onDisable()
[429] 	{
[430] 		$this->getServer()->getPluginManager();
[431] 		$this->provider->close();
[432] 	}
[433] }
[434] 
[435] 
[436] 
[437] 
[438] 
[439] 
[440] 
[441] 

Backtrace:
#0 /src/pocketmine/Server__32bit(0): pocketmine\Server->crashDump()
#1 /src/pocketmine/plugin/PluginBase(88): Tarik02\Love\Love->onDisable()
#2 /src/pocketmine/plugin/PharPluginLoader(138): pocketmine\plugin\PluginBase->setEnabled()
#3 /src/pocketmine/plugin/PluginManager(636): pocketmine\plugin\PharPluginLoader->disablePlugin()
#4 /src/pocketmine/plugin/PluginManager(568): pocketmine\plugin\PluginManager->disablePlugin()
#5 /src/pocketmine/Server__32bit(1973): pocketmine\plugin\PluginManager->enablePlugin()
#6 /src/pocketmine/Server__32bit(1959): pocketmine\Server->enablePlugin()
#7 /src/pocketmine/Server__32bit(1716): pocketmine\Server->enablePlugins()
#8 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct()
#9 (1): ()
#10 (0): {main}(

**Comment by Tarik02** [comment]
В настройках нужно указать настройки доступа до Базы даных.

2015-07-23 10:49 GMT+03:00, MrDoni98 <notifications@github.com>:

**Comment by MrDoni98** [comment]
а без неё можно? или как создать базу данных(еще не юзал бд ни разу)

**Comment by Tarik02** [comment]
Да, нужно создать базу данных, и указать ее данные в конфиге. Я хотел
задать вопрос. Где вы нашли мой плагин?

2015-07-23 10:53 GMT+03:00, MrDoni98 <notifications@github.com>:

**Comment by MrDoni98** [comment]
в гитхабе где же ещё ))

**Comment by Tarik02** [comment]
Ого, я его недавно выложил, а тут... Лол

2015-07-23 10:56 GMT+03:00, MrDoni98 <notifications@github.com>:

**Comment by MrDoni98** [comment]
я каждый день ищу новые плагине на гитхабе, я один из http://rupocketmine.net

**Comment by MrDoni98** [comment]
Хотел предложить:
Сделайте префикс для игроков если игрок женат то красный префикс "<3" если не женат то префикса нет
